<a href="https://colab.research.google.com/github/AschHarwood/social_unrest/blob/main/adding_infodemic_indicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#Importing feature target set

In [2]:
nyt_apple_acled = pd.read_csv('https://nyc3.digitaloceanspaces.com/politicalnews/political_violence/features/nyt_cases_deaths_acled_protests_apple_mob_5_26_21.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=KSJCKUT5V42U4OBV57JG%2F20210526%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20210526T204052Z&X-Amz-Expires=259200&X-Amz-SignedHeaders=host&X-Amz-Signature=f2e5545462015ad7c412fa3e7fd2240f4a540f302d181fa39ac510b9943e2fb7')

In [17]:
nyt_apple_acled.set_index(['date', 'fips', 'sub-region', 'region'], inplace=True)

In [8]:
nyt_apple_acled.reset_index(inplace=True)

In [24]:

mean = nyt_apple_acled.groupby(['date', 'fips', 'sub-region', 'region']).mean()

In [27]:
mean.to_csv('nyt_apple_acled_transport_type_removed_5_27_21.csv')

In [28]:
mean.drop('Unnamed: 0', inplace=True, axis=1)

In [31]:
mean.reset_index(inplace=True)

In [33]:
mean

               date   fips sub-region  ... deaths  protest_count  Mobility_score
0        2020-01-07   6067    unknown  ...    0.0            1.0      136.797413
1        2020-01-07  34029    unknown  ...    0.0            1.0      136.797413
2        2020-01-08   8031    unknown  ...    0.0            1.0      136.797413
3        2020-01-08  36001    unknown  ...    0.0            1.0      136.797413
4        2020-01-09  34021    unknown  ...    0.0            1.0      136.797413
...             ...    ...        ...  ...    ...            ...             ...
1505603  2021-05-24  72153    unknown  ...    0.0            0.0      136.797413
1505604  2021-05-24  72999    unknown  ...    0.0            0.0      136.797413
1505605  2021-05-24  78010    unknown  ...    0.0            0.0      136.797413
1505606  2021-05-24  78020    unknown  ...    0.0            0.0      136.797413
1505607  2021-05-24  78030    unknown  ...    0.0            0.0      136.797413

[1505608 rows x 12 columns]

In [29]:
def add_zero(x):
  if len(x) == 4:
    fips = '0' + x
    return fips
  else:
    return x

In [34]:
mean.fips = mean.fips.astype('str')
mean.fips = mean.fips.apply(lambda x: add_zero(x))

# Infoodemic data

In [35]:
info = pd.read_csv('https://nyc3.digitaloceanspaces.com/politicalnews/political_violence/covid_infodemic_riskj_index_USA.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=KSJCKUT5V42U4OBV57JG%2F20210526%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20210526T204453Z&X-Amz-Expires=259200&X-Amz-SignedHeaders=host&X-Amz-Signature=6e26a8afda1ab8683682203becd8c3c1bdc9679e394691089759087b1ea484c9')

In [36]:
#dropping epi columns
info = info.loc[:, : 'eco_open_close_fraction']

In [37]:
info.drop('eco_open_close_fraction', inplace=True, axis=1)

In [38]:
info.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487 entries, 0 to 486
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           487 non-null    object
 1   iso                            487 non-null    object
 2   info_tweets                    487 non-null    int64
 3   info_tweets_T                  487 non-null    int64
 4   info_tweets_RE                 487 non-null    int64
 5   info_tweets_RT                 487 non-null    int64
 6   info_tweets_local              487 non-null    int64
 7   info_tweets_verified           487 non-null    int64
 8   info_tweets_unverified         487 non-null    int64
 9   info_fact_reliable             487 non-null    int64
 10  info_fact_unreliable           487 non-null    int64
 11  info_fact_unknown              487 non-null    int64
 12  info_fact_unreliable_fraction  487 non-null    float64
 13  info_fact_shadow               487 non-null    int64
 14  info_fact_missing              487 non-null    int64
 15  info_fact_science              487 non-null    int64
 16  info_fact_msm                  487 non-null    int64
 17  info_fact_satire               487 non-null    int64
 18  info_fact_clickbait            487 non-null    int64
 19  info_fact_political            487 non-null    int64
 20  info_fact_fake                 487 non-null    int64
 21  info_fact_conspiracy           487 non-null    int64
 22  info_iri                       487 non-null    float64
 23  info_iri_T                     487 non-null    float64
 24  info_iri_RE                    487 non-null    float64
 25  info_iri_RT                    487 non-null    float64
 26  info_dyn_iri                   487 non-null    float64
 27  info_dyn_iri_RE                487 non-null    float64
 28  info_dyn_iri_RT                487 non-null    float64
dtypes: float64(8), int64(19), object(2)
memory usage: 110.5+ KB

In [39]:
info.drop('iso', inplace=True, axis=1)

In [40]:
info['date'] = pd.to_datetime(info['date'])

In [41]:
info.set_index('date',inplace=True)
info

            info_tweets  info_tweets_T  ...  info_dyn_iri_RE  info_dyn_iri_RT
date                                    ...
2020-01-22        54427          12407  ...           0.2103           0.3600
2020-01-23       103641          22449  ...           0.3014           0.3705
2020-01-24       195345          47325  ...           0.2585           0.3324
2020-01-25       237337          41109  ...           0.2831           0.3015
2020-01-26       266959          50400  ...           0.3549           0.3727
...                 ...            ...  ...              ...              ...
2021-05-18       281825          71152  ...           0.3220           0.4899
2021-05-19       257233          70108  ...           0.2919           0.3461
2021-05-20       251876          69180  ...           0.2635           0.3682
2021-05-21       232462          65051  ...           0.2834           0.3805
2021-05-22       189186          45800  ...           0.3504           0.3511

[487 rows x 27 columns]

# Joining Data Sets

In [42]:
mean

               date   fips sub-region  ... deaths  protest_count  Mobility_score
0        2020-01-07  06067    unknown  ...    0.0            1.0      136.797413
1        2020-01-07  34029    unknown  ...    0.0            1.0      136.797413
2        2020-01-08  08031    unknown  ...    0.0            1.0      136.797413
3        2020-01-08  36001    unknown  ...    0.0            1.0      136.797413
4        2020-01-09  34021    unknown  ...    0.0            1.0      136.797413
...             ...    ...        ...  ...    ...            ...             ...
1505603  2021-05-24  72153    unknown  ...    0.0            0.0      136.797413
1505604  2021-05-24  72999    unknown  ...    0.0            0.0      136.797413
1505605  2021-05-24  78010    unknown  ...    0.0            0.0      136.797413
1505606  2021-05-24  78020    unknown  ...    0.0            0.0      136.797413
1505607  2021-05-24  78030    unknown  ...    0.0            0.0      136.797413

[1505608 rows x 12 columns]

In [43]:
mean.set_index('date', inplace=True)

In [44]:
joined = mean.join(info, how='outer')

In [46]:
joined['2020-01-22':]

             fips sub-region  ... info_dyn_iri_RE  info_dyn_iri_RT
date                          ...
2020-01-22  01001    Alabama  ...          0.2103             0.36
2020-01-22  01003    Alabama  ...          0.2103             0.36
2020-01-22  01005    Alabama  ...          0.2103             0.36
2020-01-22  01007    Alabama  ...          0.2103             0.36
2020-01-22  01009    Alabama  ...          0.2103             0.36
...           ...        ...  ...             ...              ...
2021-05-24  72153    unknown  ...             NaN              NaN
2021-05-24  72999    unknown  ...             NaN              NaN
2021-05-24  78010    unknown  ...             NaN              NaN
2021-05-24  78020    unknown  ...             NaN              NaN
2021-05-24  78030    unknown  ...             NaN              NaN

[1486802 rows x 38 columns]

In [56]:
joined.reset_index(inplace=True)

In [57]:
joined.set_index(['date', 'fips', 'sub-region', 'region'], inplace=True)

In [105]:
joined[18805:]

                                                   cases_avg  ...  info_dyn_iri_RT
date       fips  sub-region     region                        ...
2020-01-21 78030 Virgin Islands st. thomas island   3.745756  ...              NaN
2020-01-22 01001 Alabama        autauga county     28.724634  ...             0.36
           01003 Alabama        baldwin county     28.724634  ...             0.36
           01005 Alabama        barbour county     28.724634  ...             0.36
           01007 Alabama        bibb county        28.724634  ...             0.36
...                                                      ...  ...              ...
2021-05-24 72153 unknown        unknown             1.330000  ...              NaN
           72999 unknown        unknown             6.000000  ...              NaN
           78010 unknown        unknown             1.710000  ...              NaN
           78020 unknown        unknown             0.860000  ...              NaN
           78030 unknown        unknown            14.000000  ...              NaN

[1486803 rows x 35 columns]

In [106]:

test_inter = joined.interpolate(method='linear', axis=0, limit_direction='backward')

In [107]:
test_inter = test_inter.interpolate(method='linear', axis=0, limit_direction='forward')

In [108]:
test_inter

                                     cases_avg  ...  info_dyn_iri_RT
date       fips  sub-region region              ...
2020-01-07 06067 unknown    unknown       0.00  ...           0.3600
           34029 unknown    unknown       0.00  ...           0.3600
2020-01-08 08031 unknown    unknown       0.00  ...           0.3600
           36001 unknown    unknown       0.00  ...           0.3600
2020-01-09 34021 unknown    unknown       0.00  ...           0.3600
...                                        ...  ...              ...
2021-05-24 72153 unknown    unknown       1.33  ...           0.3511
           72999 unknown    unknown       6.00  ...           0.3511
           78010 unknown    unknown       1.71  ...           0.3511
           78020 unknown    unknown       0.86  ...           0.3511
           78030 unknown    unknown      14.00  ...           0.3511

[1505608 rows x 35 columns]

In [110]:
test_inter.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1505608 entries, (Timestamp('2020-01-07 00:00:00'), '06067', 'unknown', 'unknown') to (Timestamp('2021-05-24 00:00:00'), '78030', 'unknown', 'unknown')
Data columns (total 35 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   cases_avg                      1505608 non-null  float64
 1   cases_avg_per_100k             1505608 non-null  float64
 2   deaths_avg                     1505608 non-null  float64
 3   deaths_avg_per_100k            1505608 non-null  float64
 4   cases                          1505608 non-null  float64
 5   deaths                         1505608 non-null  float64
 6   protest_count                  1505608 non-null  float64
 7   Mobility_score                 1505608 non-null  float64
 8   info_tweets                    1505608 non-null  float64
 9   info_tweets_T                  1505608 non-null  float64
 10  info_tweets_RE                 1505608 non-null  float64
 11  info_tweets_RT                 1505608 non-null  float64
 12  info_tweets_local              1505608 non-null  float64
 13  info_tweets_verified           1505608 non-null  float64
 14  info_tweets_unverified         1505608 non-null  float64
 15  info_fact_reliable             1505608 non-null  float64
 16  info_fact_unreliable           1505608 non-null  float64
 17  info_fact_unknown              1505608 non-null  float64
 18  info_fact_unreliable_fraction  1505608 non-null  float64
 19  info_fact_shadow               1505608 non-null  float64
 20  info_fact_missing              1505608 non-null  float64
 21  info_fact_science              1505608 non-null  float64
 22  info_fact_msm                  1505608 non-null  float64
 23  info_fact_satire               1505608 non-null  float64
 24  info_fact_clickbait            1505608 non-null  float64
 25  info_fact_political            1505608 non-null  float64
 26  info_fact_fake                 1505608 non-null  float64
 27  info_fact_conspiracy           1505608 non-null  float64
 28  info_iri                       1505608 non-null  float64
 29  info_iri_T                     1505608 non-null  float64
 30  info_iri_RE                    1505608 non-null  float64
 31  info_iri_RT                    1505608 non-null  float64
 32  info_dyn_iri                   1505608 non-null  float64
 33  info_dyn_iri_RE                1505608 non-null  float64
 34  info_dyn_iri_RT                1505608 non-null  float64
dtypes: float64(35)
memory usage: 412.3+ MB

In [113]:
test_inter.to_csv('nyt_cases_deaths_acled_protests_infodemic_index_5_27_21.csv')

In [112]:
joined.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1505608 entries, (Timestamp('2020-01-07 00:00:00'), '06067', 'unknown', 'unknown') to (Timestamp('2021-05-24 00:00:00'), '78030', 'unknown', 'unknown')
Data columns (total 35 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   cases_avg                      1505608 non-null  float64
 1   cases_avg_per_100k             1505608 non-null  float64
 2   deaths_avg                     1505608 non-null  float64
 3   deaths_avg_per_100k            1505608 non-null  float64
 4   cases                          1505608 non-null  float64
 5   deaths                         1505608 non-null  float64
 6   protest_count                  1505608 non-null  float64
 7   Mobility_score                 1505608 non-null  float64
 8   info_tweets                    1480312 non-null  float64
 9   info_tweets_T                  1480312 non-null  float64
 10  info_tweets_RE                 1480312 non-null  float64
 11  info_tweets_RT                 1480312 non-null  float64
 12  info_tweets_local              1480312 non-null  float64
 13  info_tweets_verified           1480312 non-null  float64
 14  info_tweets_unverified         1480312 non-null  float64
 15  info_fact_reliable             1480312 non-null  float64
 16  info_fact_unreliable           1480312 non-null  float64
 17  info_fact_unknown              1480312 non-null  float64
 18  info_fact_unreliable_fraction  1480312 non-null  float64
 19  info_fact_shadow               1480312 non-null  float64
 20  info_fact_missing              1480312 non-null  float64
 21  info_fact_science              1480312 non-null  float64
 22  info_fact_msm                  1480312 non-null  float64
 23  info_fact_satire               1480312 non-null  float64
 24  info_fact_clickbait            1480312 non-null  float64
 25  info_fact_political            1480312 non-null  float64
 26  info_fact_fake                 1480312 non-null  float64
 27  info_fact_conspiracy           1480312 non-null  float64
 28  info_iri                       1480312 non-null  float64
 29  info_iri_T                     1480312 non-null  float64
 30  info_iri_RE                    1480312 non-null  float64
 31  info_iri_RT                    1480312 non-null  float64
 32  info_dyn_iri                   1480312 non-null  float64
 33  info_dyn_iri_RE                1480312 non-null  float64
 34  info_dyn_iri_RT                1480312 non-null  float64
dtypes: float64(35)
memory usage: 412.3+ MB